name: CI Quality Checks

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  quality:
    name: Code Quality & Type Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npm run db:generate

      - name: Type check
        run: npm run type-check

      - name: Lint check
        run: npm run lint

      - name: Format check
        run: npm run format:check

      - name: Check for dead code
        run: npm run find-dead-code
        continue-on-error: true  # Don't fail build, just warn

      - name: Check for unused dependencies
        run: npm run check-deps
        continue-on-error: true  # Don't fail build, just warn

      - name: Build application
        run: npm run build
        env:
          # Railway will handle actual deployment with real env vars
          # These are just for build validation
          DATABASE_URL: ${{ secrets.DATABASE_URL || 'mongodb://localhost:27017/test' }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET || 'test-secret-min-32-chars-long-for-ci' }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL || 'https://your-app.railway.app' }}

  # Railway deployment happens automatically after this succeeds
  # No deployment steps needed here - Railway monitors the main branch
